# Generated by Django 3.2.18 on 2023-02-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_flag',
            field=models.BooleanField(default=False),
        ),
    ]
